CC = gcc
NAME = program

UNITY = ./Unity/src/unity.c

list:
	$(CC) $(UNITY) test_list.c -g -o $(NAME)

forward_list:
	$(CC) $(UNITY) test_forward_list.c -g -o $(NAME)

vector:
	$(CC) $(UNITY) test_vector.c -g -o $(NAME)

deque:
	$(CC) $(UNITY) test_deque.c -g -o $(NAME)

static_vector:
	$(CC) $(UNITY) test_static_vector.c -g -o $(NAME)

static_deque:
	$(CC) $(UNITY) test_static_deque.c -g -o $(NAME)
