CC = gcc
CFLAGS = -Wall -Wextra
NAME = program

UNITY = ./Unity/src/unity.c

algorithm:
	$(CC) $(UNITY) test_algorithm.c -g -o $(NAME) $(CFLAGS)

string:
	$(CC) $(UNITY) test_string.c -g -o $(NAME) $(CFLAGS)

list:
	$(CC) $(UNITY) test_list.c -g -o $(NAME) $(CFLAGS)

forward_list:
	$(CC) $(UNITY) test_forward_list.c -g -o $(NAME) $(CFLAGS)

vector:
	$(CC) $(UNITY) test_vector.c -g -o $(NAME) $(CFLAGS)

stack:
	$(CC) $(UNITY) test_stack.c -g -o $(NAME) $(CFLAGS)

deque:
	$(CC) $(UNITY) test_deque.c -g -o $(NAME) $(CFLAGS)

queue:
	$(CC) $(UNITY) test_queue.c -g -o $(NAME) $(CFLAGS)

set:
	$(CC) $(UNITY) test_set.c -g -o $(NAME) $(CFLAGS)

unordered_set:
	$(CC) $(UNITY) test_unordered_set.c -g -o $(NAME) $(CFLAGS)

map:
	$(CC) $(UNITY) test_map.c -g -o $(NAME) $(CFLAGS)

unordered_map:
	$(CC) $(UNITY) test_unordered_map.c -g -o $(NAME) $(CFLAGS)

priority_queue:
	$(CC) $(UNITY) test_priority_queue.c -g -o $(NAME) $(CFLAGS)

static_stack:
	$(CC) $(UNITY) test_static_stack.c -g -o $(NAME) $(CFLAGS)

static_vector:
	$(CC) $(UNITY) test_static_vector.c -g -o $(NAME) $(CFLAGS)

static_deque:
	$(CC) $(UNITY) test_static_deque.c -g -o $(NAME) $(CFLAGS)

static_priority_queue:
	$(CC) $(UNITY) test_static_priority_queue.c -g -o $(NAME) $(CFLAGS)

static_queue:
	$(CC) $(UNITY) test_static_queue.c -g -o $(NAME) $(CFLAGS)

static_unordered_map:
	$(CC) $(UNITY) test_static_unordered_map.c -g -o $(NAME) $(CFLAGS)

static_unordered_set:
	$(CC) $(UNITY) test_static_unordered_set.c -g -o $(NAME) $(CFLAGS)

all:
	$(CC) $(UNITY) test_algorithm.c -g -o $(NAME) $(CFLAGS)
	./$(NAME)

	$(CC) $(UNITY) test_list.c -g -o $(NAME) $(CFLAGS)
	./$(NAME)

	$(CC) $(UNITY) test_forward_list.c -g -o $(NAME) $(CFLAGS)
	./$(NAME)

	$(CC) $(UNITY) test_vector.c -g -o $(NAME) $(CFLAGS)
	./$(NAME)

	$(CC) $(UNITY) test_stack.c -g -o $(NAME) $(CFLAGS)
	./$(NAME)

	$(CC) $(UNITY) test_deque.c -g -o $(NAME) $(CFLAGS)
	./$(NAME)

	$(CC) $(UNITY) test_queue.c -g -o $(NAME) $(CFLAGS)
	./$(NAME)

	$(CC) $(UNITY) test_set.c -g -o $(NAME) $(CFLAGS)
	./$(NAME)

	$(CC) $(UNITY) test_unordered_set.c -g -o $(NAME) $(CFLAGS)
	./$(NAME)

	$(CC) $(UNITY) test_map.c -g -o $(NAME) $(CFLAGS)
	./$(NAME)

	$(CC) $(UNITY) test_unordered_map.c -g -o $(NAME) $(CFLAGS)
	./$(NAME)

	$(CC) $(UNITY) test_priority_queue.c -g -o $(NAME) $(CFLAGS)
	./$(NAME)

	$(CC) $(UNITY) test_static_stack.c -g -o $(NAME) $(CFLAGS)
	./$(NAME)

	$(CC) $(UNITY) test_static_vector.c -g -o $(NAME) $(CFLAGS)
	./$(NAME)

	$(CC) $(UNITY) test_static_deque.c -g -o $(NAME) $(CFLAGS)
	./$(NAME)

	$(CC) $(UNITY) test_static_priority_queue.c -g -o $(NAME) $(CFLAGS)
	./$(NAME)

	$(CC) $(UNITY) test_static_queue.c -g -o $(NAME) $(CFLAGS)
	./$(NAME)

	$(CC) $(UNITY) test_static_unordered_map.c -g -o $(NAME) $(CFLAGS)
	./$(NAME)

	$(CC) $(UNITY) test_static_unordered_set.c -g -o $(NAME) $(CFLAGS)
	./$(NAME)

	rm $(NAME)

