all:
	gcc vector.c -o vector -I ../include
	gcc map.c -o map -I ../include
	gcc fs.c -o fs -I ../include
	gcc algorithm.c -o algorithm -I ../include
	gcc struct.c -o struct -I ../include
	gcc string.c -o string -I ../include
	gcc list_of_vectors.c -o list_of_vectors -I ../include
	gcc error.c -o error -I ../include
	gcc separate_compilation.c sp_definitions.c -o separate_compilation -I ../include

clean:
	rm vector map fs algorithm struct string list_of_vectors error separate_compilation
