name: win-msys2-clang-ci

on:
  push:
    branches:
      - master
      - feature/**
      - improvement/**
      - bugfix/**

  pull_request:
    branches:
      - master
      - feature/**
      - improvement/**
      - bugfix/**

jobs:
  windows-mingw:
    if: >-
      ! contains(toJSON(github.event.commits.*.message), '[skip ci]') &&
      ! contains(toJSON(github.event.commits.*.message), '[skip github]')

    name: ${{ matrix.msystem }}
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
      matrix:
        include:
          - msystem: "MINGW64"
            install: >-
              git mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja 
              mingw-w64-x86_64-clang
            type: Release
          - msystem: "MINGW32"
            install: >-
              git mingw-w64-i686-cmake mingw-w64-i686-ninja 
              mingw-w64-i686-clang
            type: Release
          - msystem: "MINGW64"
            install: >- 
              git mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja 
              mingw-w64-x86_64-clang
            type: Debug
          - msystem: "MINGW32"
            install: >-
              git mingw-w64-i686-cmake mingw-w64-i686-ninja 
              mingw-w64-i686-clang
            type: Debug
    env:
      CMAKE_GENERATOR: Ninja

    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ${{ matrix.msystem }}
          install: ${{ matrix.install }}

      - name: Install dependencies
        run: script/ci_install_deps.sh

      - name: Configure
        run: >- 
          cmake -DCMAKE_CXX_COMPILER=clang++ -S test -B build 
          -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build -j ${{ steps.cores.outputs.count }}

      - name: Run
        working-directory: build
        run: ctest --output-on-failure -j ${{ steps.cores.outputs.count }}
